# Generated by Django 5.1 on 2025-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10, null=True),
        ),
    ]
