# Generated by Django 5.1 on 2025-12-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Finance', 'Finance'), ('Tech_Digital', 'Tech & Digital'), ('Health_Lifestyle', 'Health & Lifestyle'), ('Career', 'Career'), ('Creative_Skills', 'Creative Skills'), ('Personal_Development', 'Personal Development'), ('Language', 'Language & Cultural Exchange')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('background', models.TextField()),
                ('years_experience', models.IntegerField()),
                ('profile_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('session_length', models.IntegerField(default=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
