# Generated by Django 5.1 on 2025-12-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtime',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1),
            preserve_default=False,
        ),
    ]
