# Generated by Django 5.1 on 2025-11-27 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='data_created',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
