# Generated by Django 5.1 on 2025-12-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_remove_fundraiser_data_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='description',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='fundraiser',
            old_name='image',
            new_name='profile_url',
        ),
        migrations.RenameField(
            model_name='fundraiser',
            old_name='goal',
            new_name='years_experience',
        ),
        migrations.RenameField(
            model_name='pledge',
            old_name='supporter',
            new_name='mentee',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='comment',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Tech_Digital', 'Tech & Digital'), ('Health_Lifestyle', 'Health & Lifestyle'), ('Career', 'Career'), ('Creative_Skills', 'Creative Skills'), ('Personal_Development', 'Personal Development'), ('Language', 'Language & Cultural Exchange')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='is_accepting_mentees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='session_length',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_time', to='fundraisers.fundraiser')),
            ],
        ),
        migrations.AddField(
            model_name='pledge',
            name='booking_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='fundraisers.bookingtime'),
            preserve_default=False,
        ),
    ]
