# Generated by Django 5.1 on 2025-12-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_bookingtime_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtime',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='session_length',
            field=models.IntegerField(),
        ),
    ]
