# Generated by Django 5.1 on 2025-12-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_remove_bookingtime_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='session_length',
            field=models.IntegerField(default=30),
        ),
    ]
